Updated docker compose files, .gitmodule for new service simulation
MiSArch/infrastructure-docker pull request #301
Opened 2024-04-18 08:51 UTC by KiLanger

2024-04-22 06:52 UTC, KiLanger commented
> you should also adapt the MISARCH_SHIPMENT_PROVIDER_ENDPOINT env variable for shipment also, does payment have sth similar?

For payment, its defined on the service level (in the `docker-compose-base.yaml`)
In my opinion, that makes sense, since there are already multiple service level variables (will be changeable via experiment-config service)

2024-04-22 06:54 UTC, KiLanger commented on docker-compose.yaml
> +      - "15672:15672"
It makes the simulation queueing more transparent.
We also expose dar-redis which is a similar context in my opinion.

2024-05-01 10:05 UTC, nk-coding requested changes
env variable(s) to configure endpoints still missing

2024-05-02 05:41 UTC, KiLanger commented on docker-compose.yaml
> +      - "7000:8080"
This is the simulation endpoint ? :D
Required to manually update payments ands shipments

2024-05-02 05:45 UTC, nk-coding commented on docker-compose.yaml
> +      - "7000:8080"
Oooh, I totally forgot about this feature again

2024-05-02 06:35 UTC, nk-coding requested changes
isn't the dev docker compose file still missing the env variables?

2024-05-02 08:32 UTC, nk-coding approved these changes

2024-05-14 11:38 UTC, merged